### ISSUE TITLE
Rancher Helm Chart installed Rancher UI not working in RKE2 built in AWS built using rke2-aws-tf Terraform project using the AWS cloud-enabled example

### ISSUE THREAD

**Issue by hectoralicea** [rancherfederal/rke2-aws-tf#39]
I created an RKE2 cluster (v1.18.13+rke2r1) in AWS using this Terraform project (https://github.com/rancherfederal/rke2-aws-tf) using the cloud-enabled example for AWS.  The working terraform project was configured to build  3 autoscaling nodes and 1 server.

The RKE2 cluster appears to work just fine.  kubectl works great and  I’m able to deploy a highly customized Jenkins helm chart with no issues. ELB for service creates with no issues, etc.

Now I’m deploying the rancher helm chart into my RKE2 as follows:
```
helm upgrade rancher rancher-stable/rancher --install \
      --version v2.5.7 \
      --namespace cattle-system \
      --debug --wait --timeout 5m \
      --set hostname=rke-test.k8s.hla-associates.info \
      --set ingress.tls.source=rancher \
      --set ingress.enabled=true \
      --set tls=external
```

- Appears the built in ingress that rancher helm chart creates, terminates on port 80 of one of the VM nodes, rather than an AWS ALB.
- Appears the security group for the Node does not include port 80 or 443.
- I can reach port 22 and ssh in, but cannot reach ports 80 or 443, unless I manually add them.  Even when I do I get an 404 from the ingress.

Questions:

1. I would think that Rancher helm deploy to RKE2 on AWS would create an Ingress that would build up an AWS Load Balancer, rather than having to terminate at a Node VM.  What If I wanted to have ingress load balanced against more than 1 node. How would I get that to work that way?
2. I would think that Rancher should have added port 80 and 443 to the security group as part of provisioning the ingress.  How would get that to work that way?
3. I was told on the RKE2 issues board that RKE2 does support running the Rancher Management Console?  So perhaps its how this TF IaC sets up the AWS Cloud Provider for Kubernetes and how it works within RKE2.

**Comment by capta1nk1rk** [comment]
Hector,
Keep in mind these terraform scripts are provided for convenience, and are not "official" in that sense.  That being said, I'd like to address your issues.

Question 1:
The reason that the scripts do not deploy an AWS Load Balancer by default, is that these terraform scripts are meant as a starting point to be as non-opinionated as possible.  There are a variety of different options that could work for ingress load balancing in EC2, such as ELBs, ALBs, and NLBs just to name a few.  Ingress load balancers are traditionally created "out-of-bounds" with respect to the main control plane cluster, hence the options are left open.  If you would like an example of using RKE2 and Rancher with HA and LB inside EC2, I would suggest the following documentation articles:
[HA RKE2 + Rancher](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha/)
[Rancher /w AWS NLB](https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/nlb/)

One potential way you could use this with the terraform scripts would be to create multiple agent pools (agent-nodepool module), one of which would be tagged as ingress.  Then, the NLBs could be directed to those dedicated nodes for load balancing.  

Question 2:
We take security very seriously here at Rancher Federal, hence these scripts create a cluster with the concept of least privileged, or "secure by default".  Hence, as you noticed, ports 80 and 443 are not part of the security group.  If you wish, you could modify the logic in examples/cloud-enabled/main.tf around line 181.  Copying that block of logic and extending it to port 80 and 443 maybe achieve what you are looking for in your environment.

Question 3:
Yes, RKE2 does support running the MCM.  Your issues are related to the TF IaC.

**Comment by hectoralicea** [comment]
Re: >>>Keep in mind these terraform scripts are provided for convenience, and are not "official" in that sense. 

That's too bad.  Both AKS and EKS can launch a kubernetes cluster with a single command line (e.g. `eksctrl` and `az aks`). OpenShift has a production quality CloudFormation script at https://github.com/aws-quickstart/quickstart-redhat-openshift.

It's a shame that there is no production quality RKE2 bootstrap for Azure or AWS (using the appropriate K8S cloud providers) that would allow me to install a production configured quality cluster as quickly as you can with `eksctrl` and `az aks`

Is this capability on the roadmap for RKE2?  The ability to launch a RKE2 using either a simple single line command or a problem set of terraform scripts?

**Comment by aleiner** [comment]
Any feature requests for RKE2 would need to be submitted to SUSE / Rancher Labs via the RKE2 github page: https://github.com/rancher/rke2
