### ISSUE TITLE
Use of Auto Scale Groups is Problematic in RKE2 with etcd

### ISSUE THREAD

**Issue by ekristen** [rancherfederal/rke2-aws-tf#40]
First, thanks for the work on this, it's a great stepping stone.

Forgive me if I'm missing something and if so please point it out ...

Unfortunately the use of Auto Scale groups without additional scripting for RKE2 cluster management either via lambda or some other means that using ASGs can seriously cripple the cluster if people don't know what they are doing.

ASG for the servers, the problem here is that while additive is OK, remove/subtract or replace is not. For example, if you update the launch config to change the instance size and do an ASG refresh, all your servers will get replaced and etcd will be lost. If you do a refresh with one server at a time, you have to manually go in and remove the old node so the new node will join, otherwise it'll complain about etcd not being healthy.

ASG to agents, while this isn't as big of a problem, any time an agent is replaced or removed the old entry will remain, unsure what this means for when the node gets the same IP and DNS later down the line, could be problematic.

**Comment by kdalporto** [comment]
I'm currently running into this issue while trying to keep the AMI's up to date with the latest patches and having the ASG utilize the new AMI's. Has there been any work or temporary resolution to this problem?

**Comment by kdalporto** [comment]
@ekristen Thanks for the information! I'm curious, have you looked into how to maintain high availability and fault tolerance that the ASG theoretically would provide without using an ASG? Or potentially other solutions to like Cluster Autoscaler (https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cluster-autoscaler/amazon/)?

I'm curious what route you decided to take given the issues with ASG's and RKE2.

**Comment by aleiner** [comment]
There is inherit risks involved in using ASGs with etcd.  If you prefer to manually build ec2 instances, please look at using our ansible code for your RKE2 deployments.
