### ISSUE TITLE
Examples don't work in RHEL8. NGINX Backend, CoreDNS, Metrics server left in crash loop. 

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [rancherfederal/rke2-aws-tf#47]
I seem oddly unable to make any use of this module at all. When I deploy the example TF files (quickstart and cloud-enabled) I get a wonky deployment that has the NGINX Backend, CoreDNS, and Metrics pods cycle repeatedly in a crash loop

Steps I performed:
1. `cd` into the quickstart or cloud-enabled folder
2. Make sure your AWS credentials are set to a govcloud account (i.e. set AWS_PROFILE)
3. terraform init
4. terraform apply -auto-approve
5. export KUBECONFIG=$PWD/rke2.yaml
6. kubectl get pods -n kube-system
7. Notice these 3 pods failing
![image](https://user-images.githubusercontent.com/66089890/131019605-4382b87f-5bc9-4d15-a788-700bba1a79ce.png)
Also fetching logs from these containers provided no insight as to what's happening
```
quickstart> kubectl logs -n kube-system rke2-coredns-rke2-coredns-6f7676fdf7-p9z7z -p
.:53
[INFO] plugin/reload: Running configuration MD5 = 7da3877dbcacfd983f39051ecafd33bd
CoreDNS-1.6.9
linux/amd64, go1.15.2b5, 17665683
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] plugin/health: Going into lameduck mode for 5s

quickstart> kubectl logs -n kube-system rke2-ingress-nginx-default-backend-65f75d6664-nrckx -p
stopping http server...

quickstart> kubectl logs -n kube-system rke2-metrics-server-5d8c549c9f-297tx -p
I0826 18:51:11.018334       1 secure_serving.go:116] Serving securely on [::]:8443
```

**Comment by aleiner** [comment]
Going to close this, but please open a new issue if problems persist.  I have been able to use EL8 with recent versions of RKE2 without issue.
