### ISSUE TITLE
statestore module not compatabile with version 4.0.0 of AWS provider

### ISSUE THREAD

**Issue by todd-skinner** [rancherfederal/rke2-aws-tf#51]
Version 4 of the AWS provider introduces some major changes `aws_s3_bucket` resource. The `acl` and `server_side_encryption_configuration` attributes now have to be set using their own corresponding resource. See https://stackoverflow.com/questions/71078462/terraform-aws-provider-error-value-for-unconfigurable-attribute-cant-configur and https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#s3-bucket-refactor

These attributes now need to be set using the `aws_s3_bucket_acl` and `aws_s3_bucket_server_side_encryption_configuration` resources

Trying to run `terraform apply` now will return the errors:
```╷
│ Error: Value for unconfigurable attribute
│
│   with module.rke2.module.statestore.aws_s3_bucket.bucket,
│   on ../../modules/statestore/main.tf line 1, in resource "aws_s3_bucket" "bucket":
│    1: resource "aws_s3_bucket" "bucket" {
│
│ Can't configure a value for "server_side_encryption_configuration": its value will be decided
│ automatically based on the result of applying this configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│
│   with module.rke2.module.statestore.aws_s3_bucket.bucket,
│   on ../../modules/statestore/main.tf line 3, in resource "aws_s3_bucket" "bucket":
│    3:   acl           = "private"
│
│ Can't configure a value for "acl": its value will be decided automatically based on the result of
│ applying this configuration.
╵```

**Comment by adamacosta** [comment]
This should have been closed by #52
