### ISSUE TITLE
How to access private IP servers and agents

### ISSUE THREAD

**Issue by ajay75** [rancherfederal/rke2-aws-tf#59]
On following the best practices for cloud-enabled example of main.tf
module rke2 and agent has subnet with public IP on changing to private-subnet, I get private IP
subnets      = module.vpc.public_subnets 

Question is how to access private IP server/agent , there should be code for bastion host when using private_subnet.

Any feedback please?

**Comment by aleiner** [comment]
Our current approach is to be as minimal and secure as possible.  We have had discussions about building a bastion host, but nothing that would be long-lived.  At this time, we recommend that you build your own bastion/jumpbox that you can use to connect.
