### ISSUE TITLE
Name length issues for nlb module

### ISSUE THREAD

**Issue by mjnagel** [rancherfederal/rke2-aws-tf#84]
I've been encountering issues with the NLB module name length:
```
Error: "name" cannot be longer than 32 characters
```
Specifically for these two lines:
- https://github.com/rancherfederal/rke2-aws-tf/blob/master/modules/nlb/main.tf#L58
- https://github.com/rancherfederal/rke2-aws-tf/blob/master/modules/nlb/main.tf#L76

I did notice there is already some name trimming/substringing happening [here](https://github.com/rancherfederal/rke2-aws-tf/blob/master/modules/nlb/main.tf#L2) but it appears the port is putting it past the limit? It looks like the current names are trimmed down to 32 characters but the ports add an extra `-` + port number (~4 characters).

I haven't had a chance to dig into this further yet, as a workaround we just shortened our name that was being passed in.

**Comment by junaid18183** [comment]
I stumbled upon this as well, here is a quick PR to fix it 

https://github.com/rancherfederal/rke2-aws-tf/pull/91

**Comment by adamacosta** [comment]
Fixed by #91
