### ISSUE TITLE
Does not work on latest RHEL AMIs. No easy way to specify release channel for binary

### ISSUE THREAD

**Issue by bellis-ai** [rancherfederal/rke2-aws-tf#86]
Currently running this on any up-to-date RHEL AMI will fail. This is due to this upstream issue, which I hope will be resolved soon:

https://github.com/rancher/rke2-selinux/issues/36

While I am aware that the latest patch that can fix this is in the testing channel, it's a little inconvenient that this terraform module has no official way to specify the release channel into the cloud-init userdata (without manually modding the script). Please correct me if I'm wrong and there's some hack that can be done using the `extra_cloud_config_config` variable.

As a feature request, it would be nice to be able to pass in the environment variables, such as "INSTALL_RKE2_CHANNEL" and have them be read into the relevant parts of the userdata scripts.

If you have any guidance for alternate workarounds, such as copying the binary file directly to the node, please let me know.

**Comment by adamacosta** [comment]
Fixed by #102
