### ISSUE TITLE
`aws_lb_target_group` logic error on long names

### ISSUE THREAD

**Issue by bellis-ai** [rancherfederal/rke2-aws-tf#92]
https://github.com/rancherfederal/rke2-aws-tf/blob/1fe22df2de5e65ba3bfc57c9524f0f916c2894f6/modules/nlb/main.tf#L58

This is problematic.

According to line 3 (https://github.com/rancherfederal/rke2-aws-tf/blob/1fe22df2de5e65ba3bfc57c9524f0f916c2894f6/modules/nlb/main.tf#L3), the maximum length of `controlplane_name` is 31 characters.

If we combine this with the `-6443` that's stuck on the end, that's 36 characters.

target groups can only have up to 32 characters. This breaks if given a long name. Please handle this scenario.

**Comment by adamacosta** [comment]
Fixed by #91
